# Generated by Django 5.0.3 on 2024-04-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='background_poster',
            field=models.ImageField(blank=True, null=True, upload_to='background_posters/'),
        ),
    ]
