# Generated by Django 5.0.3 on 2024-04-12 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_background_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='streaming_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.trailer'),
        ),
    ]
